Fixing noderesourcetopology reference.
kubernetes-sigs/node-feature-discovery pull request #1030
Opened 2023-01-12 01:24 UTC by hirenp

2023-01-12 09:04 UTC, ArangoGutierrez requested changes
Thanks for this PR! could you update the PR description with a small line detailing the change, so we keep a nice git history.

/ok-to-test

2023-01-12 19:39 UTC, hirenp commented
> Something like this should give a good starting point, doing most of the work but possibly doing some incorrect edits and missing some, too:
Thanks! That seemed to have done the trick. I tried spot checking a couple places and they look correct to me.

2023-01-13 07:54 UTC, marquiz reviewed
Thanks for the updater @hirenp. I found some mistakes, possibly because of erroneous sed script that I provided if you used them.

Could you also squash the PR into one commit and adjust the commit message accordingly, e.g. `"docs: fix internal cross-page references by injecting .md"` or smth

2023-01-13 07:54 UTC, marquiz commented on docs/get-started/introduction.md
> +[NodeResourceTopology](../usage/custom-resourcesnoderesourcetopology) custom
```suggestion
[NodeResourceTopology](../usage/custom-resources.md#noderesourcetopology) custom
```

2023-01-13 07:54 UTC, marquiz commented on docs/get-started/introduction.md
> +[NodeResourceTopology](../usage/custom-resourcesnoderesourcetopology) objects,
```suggestion
[NodeResourceTopology](../usage/custom-resources.md#noderesourcetopology) objects,
```

2023-01-13 07:54 UTC, marquiz commented on docs/get-started/introduction.md
> +[NodeResourceTopology](../usage/custom-resourcesnoderesourcetopology) objects
```suggestion
[NodeResourceTopology](../usage/custom-resources.md#noderesourcetopology) objects
```

2023-01-13 07:54 UTC, marquiz commented on docs/usage/nfd-topology-gc.md
> +(see [Topology Garbage Collector](../deployment/helmtopology-garbage-collector-parameters)
```suggestion
(see [Topology Garbage Collector](../deployment/helm.md#topology-garbage-collector-parameters)
```

2023-01-13 07:54 UTC, marquiz commented on docs/usage/nfd-topology-updater.md
> +given a configuration of resources to exclude via [`-excludeList`](../reference/topology-updater-configuration-referenceexcludelist)
```suggestion
given a configuration of resources to exclude via [`-excludeList`](../reference/topology-updater-configuration-reference.md#excludelist)
```

2023-01-13 07:54 UTC, marquiz commented on docs/usage/nfd-topology-updater.md
> +[Topology Updater parameters](../deployment/helmtopology-updater-parameters)
```suggestion
[Topology Updater parameters](../deployment/helm.md#topology-updater-parameters)
```

2023-01-13 07:54 UTC, marquiz commented on docs/usage/nfd-worker.md
> +[`core.sleepInterval`](../reference/worker-configuration-reference.html.md#coresleepinterval)
```suggestion
[`core.sleepInterval`](../reference/worker-configuration-reference.md#coresleepinterval)
```

2023-01-14 00:32 UTC, hirenp commented
> Thanks for the updater @hirenp. I found some mistakes, possibly because of erroneous sed script that I provided if you used them.
> 
> Could you also squash the PR into one commit and adjust the commit message accordingly, e.g. `"docs: fix internal cross-page references by injecting .md"` or smth

Apologies for missing those. I fixed as per your suggestions.

2023-01-16 10:22 UTC, marquiz commented
> Apologies for missing those. I fixed as per your suggestions.

Np, thanks for the update @hirenp. Looks good, now. Just one last nit: could you remove the inadvertent quotation mark (`"`, a copy-paste mistake(?))  from the end of the commit message

/retitle docs: fix internal cross-page references by injecting .md

2023-01-17 04:55 UTC, hirenp commented
> > Apologies for missing those. I fixed as per your suggestions.
> 
> Np, thanks for the update @hirenp. Looks good, now. Just one last nit: could you remove the inadvertent quotation mark (`"`, a copy-paste mistake(?)) from the end of the commit message

:man_facepalming: 

Fixed. Thanks.

2023-01-17 05:56 UTC, marquiz approved these changes
👍

2023-01-17 08:35 UTC, fmuyassarov reviewed
/lgtm

2023-01-17 08:36 UTC, merged