cpu: Expose the total number of keys for TDX
kubernetes-sigs/node-feature-discovery pull request #1079
Opened 2023-03-09 14:49 UTC by fidencio

The total amount of keys that can be used on a specific TDX system is exposed via the cgroups misc.capacity. See:

```
$ cat /sys/fs/cgroup/misc.capacity
tdx 31
```

The first step to properly manage the amount of keys present in a node is exposing it via the NFD, and that's exactly what this commit does.

An example of how it ends up being exposed via the NFD:

```
$ kubectl get node 984fee00befb.jf.intel.com -o jsonpath='{.metadata.labels}'  | jq | grep tdx.total_keys
  "feature.node.kubernetes.io/cpu-security.tdx.total_keys": "31",
```

2023-03-09 16:14 UTC, marquiz reviewed
Thanks @fidencio for the PR.

How are you planning to utilize this label in practice? So is the label actually useful for anything by itself or are you planning to turn that into an extended resource or smth? What I'm trying to understand if this is smth that we want to have that as a built-in feature label, enabled by default for all users.

Also, we need to document this new feature in `docs/usage/features.md` 
 and `docs/usage/customization-guide.md`

2023-03-09 16:14 UTC, marquiz commented on source/cpu/security_amd64.go
> +		if !strings.Contains(string(line), "tdx") {
+1 would possibly make sense to make this a bit more generic

Also, using `strings.Contains` seems very easy to provide unexpected results (if new caps with string `tdx` are added) -> shouldn't we use  e.g.`strings.HasPrefix` instead?

```suggestion
		if !strings.HasPrefix(string(line), "tdx ") {
```

2023-03-09 16:40 UTC, fidencio commented
> How are you planning to utilize this label in practice? So is the label actually useful for anything by itself or are you planning to turn that into an extended resource or smth?

That's a very good question, and sorry for my lack of explanation on this.
I wat to turn that into an exteded resource, so I'm not totally sure if this needs to be exposed as it's right now or not.
What would you suggest, @marquiz?

2023-03-09 17:54 UTC, marquiz commented
> That's a very good question, and sorry for my lack of explanation on this.

No problem, that's what the reviews are for 

> I wat to turn that into an exteded resource, so I'm not totally sure if this needs to be exposed as it's right now or not.
> What would you suggest, @marquiz?

I think my kinda (so far hidden) idea for filling these kind of usage scenarios involving extended resources would be leverage NodeFeatureRule (and possibly NodeFeature) CRD. I.e. to have support for specifying ExtendedResources in the NodeFeatureRule object, basically following the lines of Labels, Taints (#540) and Annotations (#863).

But we don't have that capability, yet. Just realized that there's not even an issue tracking that, yet -> will create one.

How would NodeFeatureRule serve your use case? One plan could be to merge this PR without the labeling part and  try to squeeze in support for ExtendedResources (in NodeFeatureRule CRD) for the next v0.13.0 release.

2023-03-09 18:12 UTC, marquiz commented
/ok-to-test

2023-03-09 19:09 UTC, ArangoGutierrez reviewed
just one nit

2023-03-09 19:09 UTC, ArangoGutierrez commented on source/cpu/security_amd64.go
> +
nit: extra line not needed

2023-03-09 19:17 UTC, zvonkok commented
@ArangoGutierrez We need that for SNP as well, the total number of ASIDs

2023-03-09 19:18 UTC, marquiz commented
> @ArangoGutierrez We need that for SNP as well, the total number of ASIDs

You mean extended resources (#1081)?

2023-03-09 19:20 UTC, zvonkok commented
@marquiz Yes and No. (1) We need the extended resource via Rule (2) cpu: Expose the total number of keys for SNP

2023-03-29 09:03 UTC, fidencio commented
@marquiz, I've updated the PR and I'll test it together with @ArangoGutierrez's work and report back very soon.

2023-03-29 09:05 UTC, ArangoGutierrez requested changes
rm trailing white space

2023-03-29 09:05 UTC, ArangoGutierrez commented on docs/usage/customization-guide.md
> +|                  |              | **`tdx.total_keys`** | int | The total amount of keys an Intel TDX (Trusted Domain Extensions) host can provide.  It's only present if `tdx.enabled` is `true`.
```suggestion
|                  |              | **`tdx.total_keys`** | int | The total amount of keys an Intel TDX (Trusted Domain Extensions) host can provide.  It's only present if `tdx.enabled` is `true`.
```

2023-03-29 09:28 UTC, fidencio commented on docs/usage/customization-guide.md
> +|                  |              | **`tdx.total_keys`** | int | The total amount of keys an Intel TDX (Trusted Domain Extensions) host can provide.  It's only present if `tdx.enabled` is `true`.
Fixed, thanks!

2023-03-29 15:12 UTC, fidencio commented
> There's still one bit missing, though, that's getting the amount of used keys. I'm working on that right now.

No, nevermind.

I've done some tests here, let me share the results:

I'm using the follow Kata Containers runtime class definition:
```yaml
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata
handler: kata
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
        feature.node.kubernetes.io/cpu-security.tdx.total_keys: "1"
```

Doing a `kubectl node describe` I can see:
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                                                Requests    Limits
  --------                                                --------    ------
  cpu                                                     950m (0%)   0 (0%)
  memory                                                  290Mi (0%)  340Mi (0%)
  ephemeral-storage                                       0 (0%)      0 (0%)
  hugepages-1Gi                                           0 (0%)      0 (0%)
  hugepages-2Mi                                           0 (0%)      0 (0%)
  feature.node.kubernetes.io/cpu-security.tdx.total_keys  0           0
```

Then when I start a pod, which has the follow definition:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-qemu-tdx
spec:
  runtimeClassName: kata
  containers:
  - name: nginx-qemu-tdx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

I can then see, as a result of `kubectl node describe`:
```yaml
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                                                Requests    Limits
  --------                                                --------    ------
  cpu                                                     1200m (0%)  0 (0%)
  memory                                                  450Mi (0%)  340Mi (0%)
  ephemeral-storage                                       0 (0%)      0 (0%)
  hugepages-1Gi                                           0 (0%)      0 (0%)
  hugepages-2Mi                                           0 (0%)      0 (0%)
  feature.node.kubernetes.io/cpu-security.tdx.total_keys  1           0
```

If I try to start a second pod, now requesting 30 keys (+1 coming from the podOverhead definition), using the definition shown below:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-qemu-tdx-2
spec:
  runtimeClassName: kata
  containers:
  - name: nginx-qemu-tdx-2
    image: nginx:1.14.2
    resources:
      limits:
        feature.node.kubernetes.io/cpu-security.tdx.total_keys: 30
    ports:
    - containerPort: 80
```

Then I can see it doesn't start:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  50s   default-scheduler  0/1 nodes are available: 1 Insufficient feature.node.kubernetes.io/cpu-security.tdx.total_keys.
```

It means the book keeping is correctly done.

2023-03-29 15:13 UTC, fidencio commented
One thing that we may figure out **later** why it happens is that although the bookkeeping is correctly done those values (coming from `kubectl describe node`) are never updated:
```
Capacity:
  cpu:                                                     128
  ephemeral-storage:                                       383957772Ki
  feature.node.kubernetes.io/cpu-security.tdx.total_keys:  31
  hugepages-1Gi:                                           0
  hugepages-2Mi:                                           0
  memory:                                                  131192364Ki
  pods:                                                    110
Allocatable:
  cpu:                                                     127
  ephemeral-storage:                                       353855482090
  feature.node.kubernetes.io/cpu-security.tdx.total_keys:  31
  hugepages-1Gi:                                           0
  hugepages-2Mi:                                           0
  memory:                                                  130565676Ki
  pods:                                                    110
```

2023-03-30 09:49 UTC, zvonkok commented
/lgtm 

Last famous words @marquiz

2023-03-30 09:53 UTC, ArangoGutierrez requested changes

2023-03-30 09:53 UTC, ArangoGutierrez commented on docs/usage/features.md
> +| **`cpu-security.tdx.total_keys`** | true   | The total amount of keys an Intel TDX enabled host can provide, based on the `/sys/fs/cgroup/misc.capacity` information.
```suggestion
| **`cpu-security.tdx.total_keys`** | int   | The total amount of keys an Intel TDX enabled host can provide, based on the `/sys/fs/cgroup/misc.capacity` information.
```

2023-03-31 07:14 UTC, fidencio commented on docs/usage/features.md
> +| **`cpu-security.tdx.total_keys`** | true   | The total amount of keys an Intel TDX enabled host can provide, based on the `/sys/fs/cgroup/misc.capacity` information.
Done!

2023-03-31 07:19 UTC, zvonkok commented
/lgtm

2023-03-31 07:21 UTC, marquiz approved these changes
Thanks @fidencio for the enhancement, looks good to me 👍

2023-03-31 07:33 UTC, merged