nfd-master: disallow unprefixed and kubernetes taints
kubernetes-sigs/node-feature-discovery pull request #1118
Opened 2023-04-05 19:18 UTC by marquiz

Disallow taints having a key with "kubernetes.io/" or "*.kubernetes.io/"
prefix. This is a precaution to protect the user from messing up with
the "official" well-known taints from Kubernetes itself. The only
exception is that the "nfd.node.kubernetes.io/" prefix is allowed.

However, there is one allowed NFD-specific namespace (and its
sub-namespaces) i.e. "feature.node.kubernetes.io" under the
kubernetes.io domain that can be used for NFD-managed taints.

Also disallow unprefixed taint keys. We don't add a default prefix to
unprefixed taints (like we do for labels) from NodeFeatureRules. This is
to prevent unpleasant surprises to users that need to manage matching
tolerations for their workloads.

2023-04-05 19:18 UTC, marquiz commented
Depends on #1117 
/hold

2023-04-06 11:57 UTC, ArangoGutierrez requested changes

2023-04-06 11:57 UTC, ArangoGutierrez commented on docs/usage/customization-guide.md
> +- tbe only exception is `feature.node.kubernetes.io/` and its sub-namespaces
```suggestion
- the only exception is `feature.node.kubernetes.io/` and its sub-namespaces
```

2023-04-06 12:56 UTC, ArangoGutierrez commented
/reopen

2023-04-06 12:58 UTC, ArangoGutierrez requested changes

2023-04-06 13:57 UTC, ArangoGutierrez commented
> Depends on #1117 /hold

/unhold

2023-04-06 13:59 UTC, ArangoGutierrez approved these changes
/lgtm

2023-04-06 13:59 UTC, merged