feat: add parameters in helm to disable/enable nfd-master and nfd-worker
kubernetes-sigs/node-feature-discovery pull request #1415
Opened 2023-10-10 15:51 UTC by AhmedGrati

Resolves #1395.

2023-10-10 15:51 UTC, AhmedGrati commented
/cc @marquiz.

2023-10-10 17:20 UTC, marquiz requested changes
Thankx @AhmedGrati for this enhancement. One comment regarding the parameter naming below.

In addition, make creation of the RBAC objects (clusterrole, clusterrolebinding, role, rolebinding and serviceaccount) conditionally dependent on the new parameters.

2023-10-10 17:20 UTC, marquiz commented on deployment/helm/node-feature-discovery/values.yaml
> +  enabled: true
We have `gc.enable`, `topologyUpdater.enable`, `prometheus.enable` so for consistency it'd be good to have this `master.enable`

```suggestion
  enable: true
```

2023-10-10 17:20 UTC, marquiz commented on deployment/helm/node-feature-discovery/values.yaml
> +  enabled: true
```suggestion
  enable: true
```

2023-10-11 12:56 UTC, marquiz approved these changes
Good improvement @AhmedGrati 
/assign @ArangoGutierrez

2023-10-11 20:27 UTC, ArangoGutierrez approved these changes
/lgtm

2023-10-11 20:31 UTC, merged