Support KUBERNETES_MASTER env variable
kubernetes-sigs/node-feature-discovery pull request #1654
Opened 2024-04-04 14:24 UTC by marquiz

Support (insecure) connections to the Kubernetes API server by setting the KUBERNETES_MASTER environment variable. This is how e.g. kubectl behaves and also matches the error message(s) from client-go package. This patch is targeted for local testing and development.

2024-04-04 14:24 UTC, marquiz commented
/assign @ArangoGutierrez @TessaIO

2024-04-04 15:28 UTC, ArangoGutierrez requested changes
If the patch is " This patch is targeted for local testing and development." 
Let's document this behaviour

2024-04-04 16:40 UTC, marquiz commented
> If the patch is " This patch is targeted for local testing and development."
> Let's document this behaviour

Hmm, I start to dislike this approach myself 🙄 This was basically added to make the unit tests in #1655 to pass. I try to think another approach to achieve this 
/hold

2024-04-05 06:36 UTC, marquiz commented
After sleeping over this 👎
/close

2024-04-05 06:36 UTC, closed without merging