nfd-master: stop node-updater pool before reconfiguring api-controller
kubernetes-sigs/node-feature-discovery pull request #1660
Opened 2024-04-08 16:51 UTC by marquiz

Prevents potential race between node-updater pool and the api-controller when re-configuring nfd-master. Reconfiguration causes a new api-controller instance to be created so nfd api lister might change in the midst of processing a node update (if the pool was running). No actual issues related to this have been identified but races (like this) should still be avoided.

2024-04-08 17:53 UTC, TessaIO approved these changes

2024-04-08 19:19 UTC, ArangoGutierrez requested changes

2024-04-08 19:19 UTC, ArangoGutierrez commented on pkg/nfd-master/nfd-master.go
> +			// Stop the nodeupdater pool so that no node updates are underway
```suggestion
			// Stop the nodeUpdaterPool so that no node updates are underway
```

2024-04-08 19:19 UTC, ArangoGutierrez commented on pkg/nfd-master/nfd-master.go
> +			// Restart the node updater pool
```suggestion
			// Restart the nodeUpdaterPool
```

2024-04-10 11:32 UTC, marquiz commented
ping @ArangoGutierrez

2024-04-15 17:15 UTC, marquiz commented
ping @ArangoGutierrez

2024-04-15 17:45 UTC, ArangoGutierrez approved these changes
/lgtm

2024-04-15 18:10 UTC, merged