[release-0.14] docs: mark v0.14 EOL'd
kubernetes-sigs/node-feature-discovery pull request #1723
Opened 2024-05-28 06:15 UTC by marquiz

2024-05-28 06:15 UTC, marquiz commented
/assign @ArangoGutierrez

2024-05-28 09:31 UTC, ArangoGutierrez requested changes
just a small nit

2024-05-28 09:31 UTC, ArangoGutierrez commented on docs/_includes/templates/content.liquid
> +            This documentation is for Node Feature Discovery version that is no longer supported. Please upgrade and visit the
```suggestion
            This documentation is for a Node Feature Discovery version that is no longer supported. Please upgrade and visit the
```

2024-05-30 10:49 UTC, marquiz commented on docs/_includes/templates/content.liquid
> +            This documentation is for Node Feature Discovery version that is no longer supported. Please upgrade and visit the
Fixed as suggested

2024-05-30 10:50 UTC, marquiz commented
/assign @PiotrProkop

2024-06-03 08:33 UTC, PiotrProkop commented
/lgtm

2024-06-03 08:36 UTC, merged