docs: describe Kubernetes version compatibility in versions page
kubernetes-sigs/node-feature-discovery pull request #1764
Opened 2024-07-08 11:10 UTC by marquiz

2024-07-08 11:17 UTC, ArangoGutierrez requested changes
let's check the 1.21 first

2024-07-08 12:23 UTC, marquiz commented
> let's check the 1.21 first

You're right. In practice we need v1.24 or later because our deployments (both Helm and kustomize) depend on [gRPC container probes](https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/)

2024-07-08 12:31 UTC, marquiz commented
Updated (bumped minimum required version to v1.24). @ArangoGutierrez PTAL

2024-07-08 12:46 UTC, ArangoGutierrez approved these changes
/lgtm

2024-07-08 12:50 UTC, merged

2024-07-09 13:38 UTC, marquiz commented
/cherry-pick release-0.16