be a bit more verbose on a required KUBECONFIG env var
kubernetes-sigs/node-feature-discovery pull request #404
Opened 2020-11-24 11:49 UTC by ArangoGutierrez

throw an error message before running `e2e-test` if `KUBECONFIG` is not defined 
 
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

2020-11-24 12:49 UTC, ArangoGutierrez commented
/assign @marquiz

2020-11-24 16:25 UTC, marquiz reviewed
Nit about the commit message subject: I'd suggest to start with a "context" (i.e. `Makefile:`) in order to better describe where this change applies to, i.e. have something like
`Makefile: require KUBECONFIG to be specified for e2e-test target`

2020-11-24 16:25 UTC, marquiz commented on Makefile
> +	@if [ -z ${KUBECONFIG} ]; then echo "[ERR] KUBECONFIG missing, must be defined" &&  exit 1; fi
nit: use `;` instead of `&&` between echo and exit

2020-11-24 17:37 UTC, ArangoGutierrez commented
Also just noted, I got to do the 404 pun !!!   PR not found LOL

2020-11-24 18:09 UTC, marquiz commented on Makefile
> +	$(GO_CMD) test -v ./test/e2e/ -args -nfd.repo=$(IMAGE_REPO) -nfd.tag=$(IMAGE_TAG_NAME) -kubeconfig=$(KUBECONFIG) -nfd.e2e-config=$(E2E_TEST_CONFIG) -ginkgo.focus="\[NFD\]"; \
Ach, I forgot this from the previous review: you shouldn't need to change this line (this `; \` is unnecessary) 

Otherwise looks good

2020-11-24 19:22 UTC, marquiz requested changes
Some nits.

Plus drop `bin/nfd-master` and `bin/nfd-worker` from the patch(!) Maybe we should add `bin/` to gitignore...

2020-11-24 19:22 UTC, marquiz commented on Makefile
> +	@if [ -z ${KUBECONFIG} ]; then echo "[ERR] KUBECONFIG missing, must be defined";  exit 1; fi
nit: double-space before `exit`

2020-11-24 19:22 UTC, marquiz commented on Makefile
> +	$(GO_CMD) test -v ./test/e2e/ -args -nfd.repo=$(IMAGE_REPO) -nfd.tag=$(IMAGE_TAG_NAME) -kubeconfig=$(KUBECONFIG) -nfd.e2e-config=$(E2E_TEST_CONFIG) -ginkgo.focus="\[NFD\]"
nit: remove trailing whitespace from the end of the line

2020-11-24 19:24 UTC, marquiz commented
> Maybe we should add `bin/` to gitignore...

#405

2020-11-24 21:35 UTC, marquiz requested changes
Please squash into one oneliner patch, and, rebase on top of latest master. Gitignore was already updated in #405 so no need to touch that

2020-11-24 21:39 UTC, ArangoGutierrez commented
> Please squash into one oneliner patch, and, rebase on top of latest master. Gitignore was already updated in #405 so no need to touch that

Done

2020-11-25 05:14 UTC, marquiz approved these changes
Thanks @ArangoGutierrez 

/lgtm

2020-11-25 05:16 UTC, merged