Add support for configurable runtime full and minimal images.
kubernetes-sigs/node-feature-discovery pull request #513
Opened 2021-04-16 08:20 UTC by rmr-silicom

2021-04-16 12:15 UTC, marquiz requested changes
Thanks for the patch @rmr-silicom!

Please document the new variables in `docs/advanced/developer-guide.md´ (in the table explaining variables for build customization)

Need to sign the CLA, too 😉 

/ok-to-test

2021-04-16 12:42 UTC, rmr-silicom commented on Makefile
> +		--build-arg RUNTIME_IMG_MINIMAL=$(RUNTIME_IMG_MINIMAL) \
Will do.

2021-04-16 12:42 UTC, rmr-silicom commented on Makefile
> +RUNTIME_IMG_MINIMAL?=gcr.io/distroless/base
Will do

2021-04-19 19:04 UTC, marquiz commented on docs/advanced/developer-guide.md
> +| BASE_IMG_MINIMAL           | Container image for target image minimal (--target minimal)       | gcr.io/distroless/base
Suggest s/Container image/Container base image/

2021-04-19 19:04 UTC, marquiz commented on Makefile
> +BASE_IMG_MINIMAL ?= gcr.io/distroless/base
nit: I think `BASE_IMAGE_FULL` and `BASE_IMAGE_MINIMAL` (without the abbreviation) would be more in line with the other variables

2021-04-20 07:42 UTC, marquiz approved these changes
I think this is a nice addition to the build customization palette and ready to get merged 😎 

/label tide/merge-method-squash
/lgtm

2021-04-20 07:42 UTC, merged