nfd-master: allow sub-namespaces of the default label ns
kubernetes-sigs/node-feature-discovery pull request #536
Opened 2021-05-26 16:00 UTC by marquiz

Allow <sub-ns>.feature.node.kubernetes.io label namespaces. Makes it
possible to have e.g. vendor specific label ns without the need to user
-extra-label-ns.

2021-08-04 15:56 UTC, ArangoGutierrez requested changes
PR looks good, maybe the only nit would be to add a comment on documentation about this? (let's keep documentation up to date )

2021-08-10 08:21 UTC, marquiz commented
> PR looks good, maybe the only nit would be to add a comment on documentation about this? (let's keep documentation up to date )

Hmm, very good point! Need to fix that. I'm pretty sure I've written the documentation once but clearly not committed it 🤔  😬

2021-08-10 08:43 UTC, marquiz commented
Documentation now added

2021-08-10 11:18 UTC, ArangoGutierrez approved these changes
/lgtm

2021-08-10 11:19 UTC, merged