cstate: Skip cstate check on arches without c-states
kubernetes-sigs/node-feature-discovery pull request #571
Opened 2021-08-13 07:42 UTC by jschintag

cstate is not available on all arches. Skip check on unsupported arches.

Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

I just copied the restrictions from pstate. If other arches have cstate, let me know.

2021-08-13 08:02 UTC, marquiz commented
#570 addresses the logging issues.

We can disable it altogether, but I think it would be bette to use conditional build with filename suffixes, like we do for the other features (like cpuid). And, do the same for pstate as well. I.e. have files `cstate_amd64.go` and `cstate_stub.go` (and pstate similarly).

2021-08-13 08:18 UTC, jschintag commented
@marquiz I'll rebase and make the changes after #570 is merged.
/hold

2021-08-13 08:50 UTC, marquiz commented
> @marquiz I'll rebase and make the changes after #570 is merged.

Perfect, thanks!

2021-08-19 09:28 UTC, jschintag commented
/unhold

2021-08-19 13:19 UTC, marquiz approved these changes
Fast response, @jschintag 👍  At a quick glance looks good to me
/ok-to-test

2021-08-19 13:25 UTC, marquiz requested changes
Actually, found one small nit

2021-08-19 13:25 UTC, marquiz commented on source/cpu/cstate_amd64.go
> +
nit: redundant in the file suffixed `_amd64`, could be dropped

2021-08-19 13:25 UTC, marquiz commented on source/cpu/pstate_amd64.go
> +
nit: redundant in the file suffixed `_amd64`, could be dropped

2021-08-19 13:29 UTC, jschintag commented
Yeah, i forgott to remove `runtime` from pstate_amd64.go
Regarding the build flags, i copied them from rdt. I can leave them out as well.

2021-08-19 14:28 UTC, marquiz commented
> Yeah, i forgott to remove `runtime` from pstate_amd64.go

OK

> Regarding the build flags, i copied them from rdt. I can leave them out as well.

Yeah, please remove (as e.g. `source/cpu/power_amd64.go` does not have that). We should prolly remove those from rdt, too (in a separate PR)

2021-08-19 14:42 UTC, marquiz approved these changes
Thanks @jschintag for this optimization 👍 

/lgtm

2021-08-19 14:43 UTC, merged