nfd-worker: add core.featureSources config option
kubernetes-sigs/node-feature-discovery pull request #605
Opened 2021-09-21 13:50 UTC by marquiz

- Add a configuration option for controlling the enabled "raw" feature
sources. This is useful e.g. in testing and development, plus it also
allows fully shutting down discovery of features that are not needed in
a deployment. Supplements core.labelSources which controls the
enablement of label sources.
-  add `-feature-sources` command line flag
Allows controlling (enable/disable) the "raw" feature detection.
Especially useful for development and testing.

2021-09-21 13:51 UTC, marquiz commented
Makes more sense (and can be tested) when #604 has been merged.
/hold

2021-11-12 07:43 UTC, marquiz commented
Rebased
/unhold

2021-11-25 07:43 UTC, marquiz commented
/hold

2021-11-29 13:41 UTC, marquiz commented
Renamed to `core.featureSources`. Now depends on #603.

2021-11-29 17:30 UTC, ArangoGutierrez commented
/test all

2021-11-29 17:34 UTC, ArangoGutierrez commented
no need for rebase, hooray! 
reviewing 
/assign

2021-11-29 17:45 UTC, ArangoGutierrez commented
> Renamed to `core.featureSources`. Now depends on #603.

#603 is now merged, we are safe to unhold

2021-11-29 17:57 UTC, ArangoGutierrez requested changes
Why is commit from https://github.com/kubernetes-sigs/node-feature-discovery/pull/671 here?

2021-12-01 15:33 UTC, ArangoGutierrez commented
> > Why is commit from #671 here?
> 
> It's a bit of a mess. Rebased on top of #673
> 
> Dependency chain #671 -> #673 -> #605

#671 and  #673 are in, we are ready for this one

/test all

2021-12-01 15:34 UTC, ArangoGutierrez commented
@marquiz rebase 😁

2021-12-02 09:06 UTC, marquiz commented
> @marquiz rebase

Rebased. Plus I fixed some mistakes that I spotted myself
/unhold

2021-12-02 09:08 UTC, marquiz commented
/assign zvonkok

2021-12-02 17:53 UTC, marquiz commented
Need to rebase and align this with #670

2021-12-02 19:23 UTC, marquiz commented
Rebased, I haven't verified this new rebase myself, though

2021-12-03 06:52 UTC, marquiz commented
> Rebased, I haven't verified this new rebase myself, though

Verified that it works as expected

2021-12-03 07:26 UTC, marquiz commented
Amended this PR with a new patch adding `-feature-sources` cmdline flag. Makes this analogous to `core.labelSources` vs. `-label-sources`

2021-12-03 14:20 UTC, ArangoGutierrez approved these changes
/lgtm

2021-12-03 14:22 UTC, merged