Detect and label CPU Model Name#270
kubernetes-sigs/node-feature-discovery pull request #621
Opened 2021-10-05 12:05 UTC by AshwiniGhanwat

**Changes made in the following files:**
- deployment/components/common/worker-mounts-combined.yaml
- deployment/components/common/worker-mounts.yaml
- deployment/helm/node-feature-discovery/templates/worker.yaml
- pkg/nfd-client/worker/nfd-worker.go
- source/config.go
- source/source_test.go
- test/e2e/e2e-test-config.example.yaml
- test/e2e/node_feature_discovery.go

**New file to generate the detect CPU Info:**
- source/cpuinfo/cpuinfo.go

**Please find below tested output:**
k8smater@k8smater-VM:~/new_05_10/node-feature-discovery$ kubectl get no -o json | jq .items[].metadata.labels   | grep cpuinfo
  "feature.node.kubernetes.io/cpuinfo-cpuinfo.cpu_MHz": "1896.002",
  "feature.node.kubernetes.io/cpuinfo-cpuinfo.cpu_family": "6",
  "feature.node.kubernetes.io/cpuinfo-cpuinfo.model": "142",
  "feature.node.kubernetes.io/cpuinfo-cpuinfo.stepping": "10",
  "feature.node.kubernetes.io/cpuinfo-cpuinfo.vendor_id": "GenuineIntel",
k8smater@k8smater-VM:~/new_05_10/node-feature-discovery$

2021-10-05 12:20 UTC, zvonkok commented
/ok-to-test

2021-10-05 12:21 UTC, digambar15 commented
Request Maintainer to add /ok-to-test tag to initiate CI tests

2021-10-05 12:23 UTC, zvonkok commented
@digambar15 Can you run `make gofmt-verify` before checking in?

2021-10-05 12:40 UTC, ArangoGutierrez requested changes
badly indented
Also a comment about the test file

2021-10-05 12:40 UTC, ArangoGutierrez commented on test/e2e/e2e-test-config.example.yaml
> +        "feature.node.kubernetes.io/cpuinfo-cpuinfo.stepping": "10"
This test could fail if not run on the same cpu-arch

2021-11-02 12:20 UTC, ArangoGutierrez requested changes

2021-11-02 12:20 UTC, ArangoGutierrez commented on source/cpuinfo/cpuinfo.go
> +Copyright 2018-2021 The Kubernetes Authors.
If this is a new file, only 2021

2021-11-11 13:42 UTC, ArangoGutierrez requested changes

2021-11-11 13:42 UTC, ArangoGutierrez commented on source/cpuinfo/cpuinfo.go
> +Copyright 2018-2021 The Kubernetes Authors.
PING*

2021-11-17 10:48 UTC, marquiz requested changes
Thanks for the PR @AshwiniGhanwat 

I think this should be implemented as part of the `source/cpu` instead of a completely new source. Even the label name suggests that: `cpu-cpuinfo.model` makes more sense (IMO) than `cpuinfo-cpuinfo.model`.

Also, I'm not entirely sure how useful `cpu_MHz` label really is. Any thoughts?

2021-12-02 19:28 UTC, ArangoGutierrez commented
> Thanks for the PR @AshwiniGhanwat
> 
> I think this should be implemented as part of the `source/cpu` instead of a completely new source. Even the label name suggests that: `cpu-cpuinfo.model` makes more sense (IMO) than `cpuinfo-cpuinfo.model`.
> 
> Also, I'm not entirely sure how useful `cpu_MHz` label really is. Any thoughts?

*PING* @AshwiniGhanwat

2021-12-13 11:25 UTC, AshwiniGhanwat commented
Closing this PR. Included all comments in https://github.com/kubernetes-sigs/node-feature-discovery/pull/700

2021-12-13 11:25 UTC, closed without merging