Add variables to feature rule spec and support backrefs
kubernetes-sigs/node-feature-discovery pull request #663
Opened 2021-11-22 12:55 UTC by marquiz

Support backreferencing of output values from previous rules. Enables
complex rule setups where custom features are further combined together
to form even more sophisticated higher level labels. The labels created
by preceding rules are available as a special 'rule.matched' feature
(for matchFeatures to use).

If referencing rules accross multiple configs/CRDs care must be taken
with the ordering. Processing order of rules in nfd-worker:

1. Static rules
2. Files from /etc/kubernetes/node-feature-discovery/custom.d/
   in alphabetical order. Subdirectories are processed by reading their
   files in alphabetical order.
3. Custom rules from main nfd-worker.conf

In nfd-master, NodeFeatureRule objects are processed in alphabetical
order (based on their metadata.name).

This patch also adds new 'vars' fields to the rule spec. Like 'labels',
it is a map of key-value pairs but no labels are generated from these.
The values specified in 'vars' are only added for backreferencing into
the 'rules.matched' feature. This may by desired in schemes where the
output of certain rules is only used as intermediate variables for other
rules and no labels out of these are wanted.

An example setup:

```
  - name: "kernel feature"
    labels:
      kernel-feature:
    matchFeatures:
      - feature: kernel.version
        matchExpressions:
          major: {op: Gt, value: ["4"]}

  - name: "intermediate var feature"
    vars:
      nolabel-feature: "true"
    matchFeatures:
      - feature: cpu.cpuid
        matchExpressions:
          AVX512F: {op: Exists}
      - feature: pci.device
        matchExpressions:
          vendor: {op: In, value: ["8086"]}
          device: {op: In, value: ["1234", "1235"]}

  - name: top-level-feature
    matchFeatures:
      - feature: rule.matched
        matchExpressions:
          kernel-feature: "true"
          nolabel-feature: "true"
```

2021-11-22 12:56 UTC, marquiz commented
Depends on #553 
/hold

2021-11-23 13:10 UTC, marquiz commented
/unhold

2021-11-23 20:06 UTC, ArangoGutierrez commented
@marquiz rebase 😁 
/assign

2021-11-23 20:18 UTC, ArangoGutierrez requested changes
from manual testing
```bash
[eduardo@fedora node-feature-discovery]$ kubectl apply -f deployment/base/nfd-crds/cr-sample.yaml 
error: error validating "deployment/base/nfd-crds/cr-sample.yaml": error validating data: ValidationError(NodeFeatureRule.spec.rules[1].matchFeatures[0]): missing required field "matchExpressions" in io.k8s-sigs.nfd.v1alpha1.NodeFeatureRule.spec.rules.matchFeatures; if you choose to ignore these errors, turn validation off with --validate=false
```

2021-11-23 21:10 UTC, marquiz commented
> @marquiz rebase 😁

Rebased. Also added support for `varsTemplate`.

Need to double-verify this and add unit tests
/hold

2021-11-24 11:12 UTC, marquiz commented
Basic unit tests added.

This depends on #668 so still on hold

2021-11-25 11:32 UTC, marquiz commented
#668 merged
/unhold

2021-11-29 17:28 UTC, ArangoGutierrez approved these changes
Tested 
/lgtm

2021-11-29 17:29 UTC, merged